import React from 'react';
import AirbnbLogo from '../../public/static/svg/logo/logo.svg';
import AirbnbLogoText from '../../public/static/svg/logo/logo_text.svg';
import BackArrow from '../../public/static/svg/register/register_room_footer_back_arrow.svg';
import ClosedEye from '../../public/static/svg/auth/closed-eye.svg';
import CloseX from '../../public/static/svg/modal/modal-close-x-icon.svg';
import Hamburger from '../../public/static/svg/header/hamburger.svg';
import Mail from '../../public/static/svg/auth/mail.svg';
import OpenedEye from '../../public/static/svg/auth/opened-eye.svg';
import Person from '../../public/static/svg/auth/person.svg';
import Warning from '../../public/static/svg/common/warning.svg';
import CounterMinus from '../../public/static/svg/common/counter/counter_minus.svg';
import CounterPlus from '../../public/static/svg/common/counter/counter_plus.svg';
import Navigation from '../../public/static/svg/register/navigation.svg';
import Upload from '../../public/static/svg/register/upload.svg';
import Pencil from '../../public/static/svg/register/photo/pencil.svg';
import TrashCan from '../../public/static/svg/register/photo/trash_can.svg';
import GrayPlus from '../../public/static/svg/register/photo/gray_plus.svg';
import CheckMark from '../../public/static/svg/register/dark_cyan_check_mark.svg';
import Search from '../../public/static/svg/search/white_search.svg';

export const AirbnbLogoIcon = React.memo(AirbnbLogo);
export const AirbnbLogoTextIcon = React.memo(AirbnbLogoText);
export const BackArrowIcon = React.memo(BackArrow);
export const ClosedEyeIcon = React.memo(ClosedEye);
export const CloseXIcon = React.memo(CloseX);
export const HamburgerIcon = React.memo(Hamburger);
export const MailIcon = React.memo(Mail);
export const OpenedEyeIcon = React.memo(OpenedEye);
export const PersonIcon = React.memo(Person);
export const WarningIcon = React.memo(Warning);
export const CounterMinusIcon = React.memo(CounterMinus);
export const CounterPlusIcon = React.memo(CounterPlus);
export const NavigationIcon = React.memo(Navigation);
export const UploadIcon = React.memo(Upload);
export const PencilIcon = React.memo(Pencil);
export const TrashCanIcon = React.memo(TrashCan);
export const GrayPlusIcon = React.memo(GrayPlus);
export const CheckMarkIcon = React.memo(CheckMark);
export const SearchIcon = React.memo(Search);
